### ISSUE TITLE
List of .java files that still need covered

### ISSUE THREAD

**Issue by tlucas-uvic** [clife/SENG426_GroupEh#18]
EChequeClient, 
ElectronicChequeJFrame, 
RSAGenerator, 
ReceivedChequeJFrame, 
RegistrationJFrame, 
SendChequeJFrame

**Comment by swbaiken** [comment]
RSAGenerator formatting updated and committed

**Comment by swbaiken** [comment]
SendChequeJFrame formatting updated
function getFileLoaction renamed to getFileLocation
Error messages modified in jBSendPTPChequeMouseClicked

**Comment by swbaiken** [comment]
ReceivedChequeJFrame is already formatted - other changes required?

**Comment by swbaiken** [comment]
ElectronicChequeJFrame formatting updated, and spelling corrected in error messages and comments

**Comment by swbaiken** [comment]
RegistrationJFrame updated formatting and spelling
Changed private function "getWalletLoaction" to "getWalletLocation"

**Comment by eburdon** [comment]
aaand that should be all of them. Close this when ready?
