### ISSUE TITLE
EchequeClient.java file name

### ISSUE THREAD

**Issue by swbaiken** [clife/SENG426_GroupEh#24]
File name should be changed to EChequeClient.java

**Comment by eburdon** [comment]
Resolved https://github.com/clife/SENG426_GroupEh/commit/a545fe2c16569440d44f185f74f4d4a477f1ae0f

**Comment by eburdon** [comment]
As per Slack, will format, take out old code, etc out of this file...

> "but there's still formatting and spelling that needs to be done on EchequeClient"

**Comment by eburdon** [comment]
Resolved https://github.com/clife/SENG426_GroupEh/pull/26
