### ISSUE TITLE
Bad practice and insecure password padding

### ISSUE THREAD

**Issue by clife** [clife/SENG426_GroupEh#3]
File: ElectronicChequeJFrame.java
Line: 335-340
Bug:
Password length must be 16 characters in order to encrypt. If the password is shorter then it gets padded by adding letters from the start of the password again in order. Ex. 'password' is padded to 'passwordpassword' and then encrypted.

**Comment by clife** [comment]
Fixed and updated to master

**Comment by swbaiken** [comment]
Is there a reason that the password is forced to be a minimum length? A larger issue is that there is nothing that handles passwords under 8 and over 16 characters. Those pass through unmodified.
Does the form handle these cases?

**Comment by clife** [comment]
I'll look into that and lock it down right now

**Comment by clife** [comment]
I would argue that rectifying the encryption scheme is beyond the scope of this project. With reference to http://stackoverflow.com/questions/992019/java-256-bit-aes-password-based-encryption/992413#992413 via http://stackoverflow.com/questions/1760785/invalid-aes-key-length-error, it looks like essentially the entire scheme would need to be rewritten
